# Generated by Django 4.2.30 on 2026-04-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField(default=4.0)),
                ('max_guests', models.IntegerField()),
                ('description', models.TextField()),
                ('images', models.JSONField(default=list)),
                ('amenities', models.JSONField(default=list)),
                ('unavailable_dates', models.JSONField(default=list)),
            ],
        ),
    ]
